// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDywp4Rt1U2Uauf3PuLg4NFGLQ1j5U9gC4',
    appId: '1:211534063431:web:f3728068a64f7e9d6b4e62',
    messagingSenderId: '211534063431',
    projectId: 'calling-app-v2',
    authDomain: 'calling-app-v2.firebaseapp.com',
    storageBucket: 'calling-app-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1jx4C4Jwaktoq6juM5MeW7IKbaZl2KfA',
    appId: '1:211534063431:android:03054d0fc774db966b4e62',
    messagingSenderId: '211534063431',
    projectId: 'calling-app-v2',
    storageBucket: 'calling-app-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB46_tcbYAfKRzEHXSZKVEhKRVtLvsURP4',
    appId: '1:211534063431:ios:92c1a221969f17196b4e62',
    messagingSenderId: '211534063431',
    projectId: 'calling-app-v2',
    storageBucket: 'calling-app-v2.firebasestorage.app',
    iosBundleId: 'com.calling.jithin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB46_tcbYAfKRzEHXSZKVEhKRVtLvsURP4',
    appId: '1:211534063431:ios:eabed9db8713a2906b4e62',
    messagingSenderId: '211534063431',
    projectId: 'calling-app-v2',
    storageBucket: 'calling-app-v2.firebasestorage.app',
    iosBundleId: 'com.example.callProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDywp4Rt1U2Uauf3PuLg4NFGLQ1j5U9gC4',
    appId: '1:211534063431:web:a4204b1c9a1e7ca06b4e62',
    messagingSenderId: '211534063431',
    projectId: 'calling-app-v2',
    authDomain: 'calling-app-v2.firebaseapp.com',
    storageBucket: 'calling-app-v2.firebasestorage.app',
  );
}
